# Generated by Django 3.2.5 on 2021-08-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tienda',
            options={'verbose_name': 'Tienda', 'verbose_name_plural': 'Tienda'},
        ),
        migrations.AddField(
            model_name='tienda',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
