# Generated by Django 3.2.5 on 2021-08-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_comprasrealizadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasrealizadas',
            name='caducidad',
            field=models.DateField(),
        ),
    ]
