# Generated by Django 3.2.5 on 2021-08-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_comprasrealizadas_caducidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasrealizadas',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
