# Generated by Django 3.2.5 on 2021-08-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210819_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('intro_content', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='blog')),
                ('content', models.TextField()),
                ('image1', models.ImageField(null=True, upload_to='blog')),
                ('content2', models.TextField(blank=True, null=True)),
                ('image2', models.ImageField(null=True, upload_to='blog')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),

    ]
