# Generated by Django 3.2.5 on 2021-08-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='blog'),
        ),
    ]
