# Generated by Django 3.2.5 on 2021-08-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210821_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='content3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
